<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FAQSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = '2026-05-12 19:24:40';

        DB::table('faqs')->insert([
            [
                'id' => 1,
                'category' => 'Quy trình và Chính sách Khách hàng',
                'question' => 'Làm thế nào để đặt lịch tư vấn?',
                'answer' => 'Duyệt danh sách luật sư theo chuyên môn, địa điểm và mức phí. Chọn một luật sư, chọn khung giờ trong hồ sơ của họ, rồi xác nhận thông tin của bạn.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'category' => 'Giải đáp thắc mắc pháp lý chuyên ngành',
                'question' => 'Tôi có thể đăng tin bất động sản của mình vừa cho thuê vừa để bán không?',
                'answer' => 'Dạ, điều này hoàn toàn có thể. Quý chủ nhà có thể đăng đồng thời tin bán và tin cho thuê cho cùng một bất động sản.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'category' => 'Sản phẩm & Dịch vụ Pháp lý',
                'question' => 'Tôi có nhận được hồ sơ dịch vụ và hóa đơn không?',
                'answer' => 'Sau khi dịch vụ hoàn tất, bạn nhận hồ sơ chi tiết trên ứng dụng. Hóa đơn điện tử sẽ được gửi qua email hoặc ứng dụng để khách hàng theo dõi lịch sử và chi phí.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'category' => 'Quy trình và Chính sách Khách hàng',
                'question' => 'Điều gì sẽ xảy ra nếu luật sư đến muộn?',
                'answer' => 'Bạn sẽ nhận thông báo từ Trang chủ. Nếu không có thông báo, vui lòng liên hệ tổng đài; hệ thống sẽ cập nhật tình hình hoặc sắp xếp luật sư khác để đảm bảo quyền lợi.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'category' => 'Quy trình và Chính sách Khách hàng',
                'question' => 'Tôi có thể thay đổi lịch hoặc hủy đặt chỗ được không?',
                'answer' => 'Có, bạn có thể thao tác trong mục Quản lý lịch hẹn. Hủy sớm sẽ miễn phí, nhưng hủy sát giờ hoặc khi luật sư đã di chuyển có thể phát sinh phí.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'category' => 'Thông tin chung',
                'question' => 'Hệ thống giữ lịch tư vấn trong bao lâu khi tôi đang thao tác?',
                'answer' => 'Khi bạn nhấn "Đặt lịch", hệ thống sẽ giữ slot trong vòng 5 phút để bạn thực hiện xác thực email trước khi giải phóng slot cho người khác.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'category' => 'Giải đáp thắc mắc pháp lý chuyên ngành',
                'question' => 'Chủ đầu tư được thu tối đa bao nhiêu tiền đặt cọc cho nhà ở tương lai?',
                'answer' => 'Chủ đầu tư dự án bất động sản chỉ được thu tiền đặt cọc không quá 5% giá bán hoặc giá cho thuê mua nhà ở/công trình hình thành trong tương lai.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'category' => 'Giải đáp thắc mắc pháp lý chuyên ngành',
                'question' => 'Độ tuổi kết hôn hợp pháp theo quy định hiện nay là bao nhiêu?',
                'answer' => 'Theo quy định mới, nam phải từ đủ 20 tuổi trở lên và nữ phải từ đủ 18 tuổi trở lên mới đủ điều kiện kết hôn.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'category' => 'Giải đáp thắc mắc pháp lý chuyên ngành',
                'question' => 'Người lao động cần báo trước bao lâu khi đơn phương chấm dứt hợp đồng?',
                'answer' => 'Ít nhất 45 ngày với hợp đồng không thời hạn, 30 ngày với hợp đồng 12-36 tháng, và ít nhất 03 ngày làm việc với hợp đồng dưới 12 tháng.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'category' => 'Thông tin chung',
                'question' => 'Làm thế nào để đánh giá mức độ uy tín của một luật sư?',
                'answer' => 'Bạn có thể dựa vào thang điểm uy tín trên hệ thống (90-100 là rất uy tín) và danh sách đánh giá 1-5 sao từ các khách hàng thực tế.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'category' => 'Sản phẩm & Dịch vụ Pháp lý',
                'question' => 'Tôi có thể tìm kiếm luật sư theo những bộ lọc nào?',
                'answer' => 'Hệ thống hỗ trợ lọc theo chuyên môn (Dân sự, Hình sự, Đất đai...), khu vực địa lý (Tỉnh/Huyện) và thời gian luật sư có lịch trống.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'category' => 'Giải đáp thắc mắc pháp lý chuyên ngành',
                'question' => 'Thế nào được coi là doanh nghiệp nhà nước theo Luật mới?',
                'answer' => 'Doanh nghiệp nhà nước bao gồm các doanh nghiệp do Nhà nước nắm giữ trên 50% vốn điều lệ hoặc tổng số cổ phần có quyền biểu quyết.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'category' => 'Giải đáp thắc mắc pháp lý chuyên ngành',
                'question' => 'Mang thai hộ vì mục đích nhân đạo được phép khi nào?',
                'answer' => 'Chỉ thực hiện khi có xác nhận y tế về việc người vợ không thể mang thai, cặp vợ chồng chưa có con chung và đã được tư vấn đầy đủ về pháp lý.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'category' => 'Quy trình và Chính sách Khách hàng',
                'question' => 'Tôi thanh toán phí tư vấn cho luật sư như thế nào?',
                'answer' => 'Bạn có thể thanh toán bằng tiền mặt trực tiếp hoặc chuyển khoản qua VNPay bằng cách quét mã QR hiển thị trên ứng dụng sau khi cuộc hẹn hoàn tất.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'category' => 'Giải đáp thắc mắc pháp lý chuyên ngành',
                'question' => 'Tài sản chung của vợ chồng trong thời kỳ hôn nhân gồm những gì?',
                'answer' => 'Gồm tài sản do vợ/chồng tạo ra, thu nhập từ lao động, sản xuất, kinh doanh, hoa lợi, lợi tức và các thu nhập hợp pháp khác phát sinh trong thời kỳ hôn nhân.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'category' => 'Thông tin chung',
                'question' => 'Tại sao tôi không thể xem danh sách lịch hẹn của mình?',
                'answer' => 'Để bảo mật thông tin, bạn bắt buộc phải đăng nhập tài khoản. Nếu chưa đăng nhập, hệ thống sẽ báo "Vui lòng đăng nhập để xem lịch hẹn".',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'category' => 'Giải đáp thắc mắc pháp lý chuyên ngành',
                'question' => 'Mức thanh toán tối đa khi mua nhà ở tương lai mà chưa bàn giao là bao nhiêu?',
                'answer' => 'Tổng số tiền thanh toán không được quá 70% giá trị hợp đồng khi chưa bàn giao nhà; riêng với bên bán có vốn đầu tư nước ngoài là không quá 50%.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'category' => 'Sản phẩm & Dịch vụ Pháp lý',
                'question' => 'Hồ sơ chi tiết của luật sư hiển thị những thông tin gì?',
                'answer' => 'Gồm họ tên, chuyên môn, Đoàn luật sư, kinh nghiệm làm việc, học vấn, vụ án tiêu biểu và các đánh giá trung bình từ người dùng khác.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'category' => 'Giải đáp thắc mắc pháp lý chuyên ngành',
                'question' => 'Tòa án có trách nhiệm hòa giải trong tố tụng dân sự không?',
                'answer' => 'Tòa án có trách nhiệm tiến hành hòa giải và tạo điều kiện thuận lợi để các đương sự thỏa thuận với nhau về việc giải quyết vụ việc dân sự theo quy định.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'category' => 'Giải đáp thắc mắc pháp lý chuyên ngành',
                'question' => 'Trợ cấp thôi việc được tính như thế nào theo luật mới?',
                'answer' => 'Mỗi năm làm việc được trợ cấp một nửa tháng tiền lương. Tiền lương tính trợ cấp là bình quân của 06 tháng liền kề trước khi thôi việc.',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
        ]);
    }
}
